name: Test

on: [push]

jobs:
  build:
    name: Build DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: pip install .

  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
        pip install -r reqs/test.txt
        pip install .

      - name: Run tests
        run: pytest test/
